// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq61AxoGM121_JrSYIpNR8eRAs1ZY1Hew',
    appId: '1:328649122836:web:ea8b7d1201f220023eb301',
    messagingSenderId: '328649122836',
    projectId: 'ysl-store-app',
    authDomain: 'ysl-store-app.firebaseapp.com',
    storageBucket: 'ysl-store-app.firebasestorage.app',
    measurementId: 'G-ZGXRQZG4E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXSuDQ1ZgdFVt3yxUaR4dclhl4PkjPHE',
    appId: '1:328649122836:android:7a2f2f99f190b38b3eb301',
    messagingSenderId: '328649122836',
    projectId: 'ysl-store-app',
    storageBucket: 'ysl-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yluKfr9YnV1YAI9PrPyja0BBnK5ptvk',
    appId: '1:328649122836:ios:ab57ac109e8e03253eb301',
    messagingSenderId: '328649122836',
    projectId: 'ysl-store-app',
    storageBucket: 'ysl-store-app.firebasestorage.app',
    androidClientId: '328649122836-2iuduln24qs5vdn0esqsas053hojmkiu.apps.googleusercontent.com',
    iosClientId: '328649122836-3gfn6c111lp3tfst36gf5unnpmt9q36g.apps.googleusercontent.com',
    iosBundleId: 'com.example.yslStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-yluKfr9YnV1YAI9PrPyja0BBnK5ptvk',
    appId: '1:328649122836:ios:ab57ac109e8e03253eb301',
    messagingSenderId: '328649122836',
    projectId: 'ysl-store-app',
    storageBucket: 'ysl-store-app.firebasestorage.app',
    androidClientId: '328649122836-2iuduln24qs5vdn0esqsas053hojmkiu.apps.googleusercontent.com',
    iosClientId: '328649122836-3gfn6c111lp3tfst36gf5unnpmt9q36g.apps.googleusercontent.com',
    iosBundleId: 'com.example.yslStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq61AxoGM121_JrSYIpNR8eRAs1ZY1Hew',
    appId: '1:328649122836:web:0dd07236b2a773603eb301',
    messagingSenderId: '328649122836',
    projectId: 'ysl-store-app',
    authDomain: 'ysl-store-app.firebaseapp.com',
    storageBucket: 'ysl-store-app.firebasestorage.app',
    measurementId: 'G-SVS6CP9JWG',
  );
}
