// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-JEwQ9R4p1X6dNHkJBjERfjY80Xe37M',
    appId: '1:222234766033:web:42acbe53c6ce9e677bf3f0',
    messagingSenderId: '222234766033',
    projectId: 'fast-food-app-kh',
    authDomain: 'fast-food-app-kh.firebaseapp.com',
    storageBucket: 'fast-food-app-kh.firebasestorage.app',
    measurementId: 'G-WH40SN327T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCqHMiB3hEv6F1tgIXvNUwDpg0yP7JYo',
    appId: '1:222234766033:android:d832185e5f83a6217bf3f0',
    messagingSenderId: '222234766033',
    projectId: 'fast-food-app-kh',
    storageBucket: 'fast-food-app-kh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvShV8KlbJaLTSgHOcFrVMz2g6lBj5So',
    appId: '1:222234766033:ios:02c5fa0834aade307bf3f0',
    messagingSenderId: '222234766033',
    projectId: 'fast-food-app-kh',
    storageBucket: 'fast-food-app-kh.firebasestorage.app',
    iosClientId: '222234766033-ianflkffltum3s6ikjtqle6v0emdgusm.apps.googleusercontent.com',
    iosBundleId: 'com.example.yslStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvShV8KlbJaLTSgHOcFrVMz2g6lBj5So',
    appId: '1:222234766033:ios:02c5fa0834aade307bf3f0',
    messagingSenderId: '222234766033',
    projectId: 'fast-food-app-kh',
    storageBucket: 'fast-food-app-kh.firebasestorage.app',
    iosClientId: '222234766033-ianflkffltum3s6ikjtqle6v0emdgusm.apps.googleusercontent.com',
    iosBundleId: 'com.example.yslStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk-JEwQ9R4p1X6dNHkJBjERfjY80Xe37M',
    appId: '1:222234766033:web:e5f57ef5e945d4067bf3f0',
    messagingSenderId: '222234766033',
    projectId: 'fast-food-app-kh',
    authDomain: 'fast-food-app-kh.firebaseapp.com',
    storageBucket: 'fast-food-app-kh.firebasestorage.app',
    measurementId: 'G-236VXS8J53',
  );
}
